# Generated by Django 3.0.4 on 2020-03-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghj_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_url', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('how_to_apply', models.CharField(max_length=100)),
                ('companyLogo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('jobs', models.ManyToManyField(related_name='joblists', to='jobswipe.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('saved_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seekers', to='jobswipe.JobList')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.ManyToManyField(related_name='jobs', to='jobswipe.Keyword'),
        ),
    ]
