# Generated by Django 3.0.4 on 2020-03-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobswipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='saved_jobs',
        ),
        migrations.AddField(
            model_name='joblist',
            name='jobseeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_lists', to='jobswipe.JobSeeker'),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
