# Generated by Django 3.0.4 on 2020-03-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobswipe', '0003_auto_20200306_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='jobs',
            field=models.ManyToManyField(to='jobswipe.Job'),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='jobseeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobswipe.JobSeeker'),
        ),
    ]
