# Generated by Django 3.0.4 on 2020-03-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobswipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved',
            old_name='jobs',
            new_name='gh_jobids',
        ),
        migrations.RenameField(
            model_name='saved',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='title',
        ),
        migrations.DeleteModel(
            name='Unreviewed',
        ),
    ]
